import gym

ATARI_DICT = dict(
    asteroids={
        "player_x": 73,
        "player_y": 74,
        "num_lives_direction": 60,
        "player_score_high": 61,
        "player_score_low": 62,
        "player_missile_x1": 83,
        "player_missile_x2": 84,
        "player_missile_y1": 86,
        "player_missile_y2": 87,
        "player_missile1_direction": 89,
        "player_missile2_direction": 90,
        "enemy_asteroids_y_0": 3,
        "enemy_asteroids_y_1": 4,
        "enemy_asteroids_y_2": 5,
        "enemy_asteroids_y_3": 6,
        "enemy_asteroids_y_4": 7,
        "enemy_asteroids_y_5": 8,
        "enemy_asteroids_y_6": 9,
        "enemy_asteroids_y_7": 12,
        "enemy_asteroids_y_8": 13,
        "enemy_asteroids_y_9": 14,
        "enemy_asteroids_y_10": 15,
        "enemy_asteroids_y_11": 16,
        "enemy_asteroids_y_12": 17,
        "enemy_asteroids_y_13": 18,
        "enemy_asteroids_y_14": 19,
        "enemy_asteroids_x_0": 21,
        "enemy_asteroids_x_1": 22,
        "enemy_asteroids_x_2": 23,
        "enemy_asteroids_x_3": 24,
        "enemy_asteroids_x_4": 25,
        "enemy_asteroids_x_5": 26,
        "enemy_asteroids_x_6": 27,
        "enemy_asteroids_x_7": 30,
        "enemy_asteroids_x_8": 31,
        "enemy_asteroids_x_9": 32,
        "enemy_asteroids_x_10": 33,
        "enemy_asteroids_x_11": 34,
        "enemy_asteroids_x_12": 35,
        "enemy_asteroids_x_13": 36,
        "enemy_asteroids_x_14": 37,
    },
    battlezone={
        "blue_tank_facing_direction": 46,
        "blue_tank_size_y": 47,
        "blue_tank_x": 48,
        "blue_tank2_facing_direction": 52,
        "blue_tank2_size_y": 53,
        "blue_tank2_x": 54,
        "num_lives": 58,
        "missile_y": 105,
        "compass_needles_angle": 84,
        "angle_of_tank": 4,
        "left_tread_position": 59,
        "right_tread_position": 60,
        "crosshairs_color": 108,
        "score": 29,
    },
    berzerk={
        "player_x": 19,
        "player_y": 11,
        "player_direction": 14,
        "player_missile_x": 22,
        "player_missile_y": 23,
        "player_missile_direction": 21,
        "robot_missile_direction": 26,
        "robot_missile_x": 29,
        "robot_missile_y": 30,
        "num_lives": 90,
        "robots_killed_count": 91,
        "game_level": 92,
        "enemy_evilOtto_x": 46,
        "enemy_evilOtto_y": 89,
        "enemy_robots_x_0": 65,
        "enemy_robots_x_1": 66,
        "enemy_robots_x_2": 67,
        "enemy_robots_x_3": 68,
        "enemy_robots_x_4": 69,
        "enemy_robots_x_5": 70,
        "enemy_robots_x_6": 71,
        "enemy_robots_x_7": 72,
        "enemy_robots_y_0": 56,
        "enemy_robots_y_1": 57,
        "enemy_robots_y_2": 58,
        "enemy_robots_y_3": 59,
        "enemy_robots_y_4": 60,
        "enemy_robots_y_5": 61,
        "enemy_robots_y_6": 62,
        "enemy_robots_y_7": 63,
        "enemy_robots_y_8": 64,
        "player_score_0": 93,
        "player_score_1": 94,
        "player_score_2": 95,
    },
    bowling={
        "ball_x": 30,
        "ball_y": 41,
        "player_x": 29,
        "player_y": 40,
        "frame_number_display": 36,
        "score": 33,
        "pin_existence_0": 57,
        "pin_existence_1": 58,
        "pin_existence_2": 59,
        "pin_existence_3": 60,
        "pin_existence_4": 61,
        "pin_existence_5": 62,
        "pin_existence_6": 63,
        "pin_existence_7": 64,
        "pin_existence_8": 65,
        "pin_existence_9": 66,
    },
    boxing={
        "player_x": 32,
        "player_y": 34,
        "enemy_x": 33,
        "enemy_y": 35,
        "enemy_score": 19,
        "clock": 17,
        "player_score": 18,
    },
    breakout={
        "ball_x": 99,
        "ball_y": 101,
        "player_x": 72,
        "blocks_hit_count": 77,
        "score": 84,
        "block_bit_map_0": 0,
        "block_bit_map_1": 1,
        "block_bit_map_2": 2,
        "block_bit_map_3": 3,
        "block_bit_map_4": 4,
        "block_bit_map_5": 5,
        "block_bit_map_6": 6,
        "block_bit_map_7": 7,
        "block_bit_map_8": 8,
        "block_bit_map_9": 9,
        "block_bit_map_10": 10,
        "block_bit_map_11": 11,
        "block_bit_map_12": 12,
        "block_bit_map_13": 13,
        "block_bit_map_14": 14,
        "block_bit_map_15": 15,
        "block_bit_map_16": 16,
        "block_bit_map_17": 17,
        "block_bit_map_18": 18,
        "block_bit_map_19": 19,
        "block_bit_map_20": 20,
        "block_bit_map_21": 21,
        "block_bit_map_22": 22,
        "block_bit_map_23": 23,
        "block_bit_map_24": 24,
        "block_bit_map_25": 25,
        "block_bit_map_26": 26,
        "block_bit_map_27": 27,
        "block_bit_map_28": 28,
        "block_bit_map_29": 29,
    },
    demonattack={
        "level": 62,
        "player_x": 22,
        "enemy_x1": 17,
        "enemy_x2": 18,
        "enemy_x3": 19,
        "missile_y": 21,
        "enemy_y1": 69,
        "enemy_y2": 70,
        "enemy_y3": 71,
        "num_lives": 114,
    },
    freeway={
        "player_y": 14,
        "score": 103,
        "enemy_car_x_0": 108,
        "enemy_car_x_1": 109,
        "enemy_car_x_2": 110,
        "enemy_car_x_3": 111,
        "enemy_car_x_4": 112,
        "enemy_car_x_5": 113,
        "enemy_car_x_6": 114,
        "enemy_car_x_7": 115,
        "enemy_car_x_8": 116,
        "enemy_car_x_9": 117,
    },
    frostbite={
        "top_row_iceflow_x": 34,
        "second_row_iceflow_x": 33,
        "third_row_iceflow_x": 32,
        "fourth_row_iceflow_x": 31,
        "enemy_bear_x": 104,
        "num_lives": 76,
        "igloo_blocks_count": 77,
        "player_x": 102,
        "player_y": 100,
        "player_direction": 4,
        "enemy_x_0": 84,
        "enemy_x_1": 85,
        "enemy_x_2": 86,
        "enemy_x_3": 87,
        "score_0": 72,
        "score_1": 73,
        "score_2": 74,
    },
    hero={
        "player_x": 27,
        "player_y": 31,
        "power_meter": 43,
        "room_number": 28,
        "level_number": 117,
        "dynamite_count": 50,
        "score_0": 56,
        "score_1": 57,
    },
    montezumarevenge={
        "room_number": 3,
        "player_x": 42,
        "player_y": 43,
        "player_direction": 52,
        "enemy_skull_x": 47,
        "enemy_skull_y": 46,
        "key_monster_x": 44,
        "key_monster_y": 45,
        "level": 57,
        "num_lives": 58,
        "items_in_inventory_count": 61,
        "room_state": 62,
        "score_0": 19,
        "score_1": 20,
        "score_2": 21,
    },
    mspacman={
        "enemy_sue_x": 6,
        "enemy_inky_x": 7,
        "enemy_pinky_x": 8,
        "enemy_blinky_x": 9,
        "enemy_sue_y": 12,
        "enemy_inky_y": 13,
        "enemy_pinky_y": 14,
        "enemy_blinky_y": 15,
        "player_x": 10,
        "player_y": 16,
        "fruit_x": 11,
        "fruit_y": 17,
        "ghosts_count": 19,
        "player_direction": 56,
        "dots_eaten_count": 119,
        "player_score": 120,
        "num_lives": 123,
    },
    pitfall={
        "player_x": 97,
        "player_y": 105,
        "enemy_logs_x": 98,
        "enemy_scorpion_x": 99,
        "bottom_of_rope_y": 18,
        "clock_sec": 89,
        "clock_min": 88,
    },
    pong={
        "player_y": 51,
        "player_x": 46,
        "enemy_y": 50,
        "enemy_x": 45,
        "ball_x": 49,
        "ball_y": 54,
        "enemy_score": 13,
        "player_score": 14,
    },
    privateeye={
        "player_x": 63,
        "player_y": 86,
        "room_number": 92,
        "player_direction": 58,
        "dove_x": 48,
        "dove_y": 39,
        "clock_0": 67,
        "clock_1": 69,
        "score_0": 73,
        "score_1": 74,
    },
    qbert={
        "player_x": 43,
        "player_y": 67,
        "player_column": 35,
        "red_enemy_column": 69,
        "green_enemy_column": 105,
        "score_0": 89,
        "score_1": 90,
        "score_2": 91,
        "tile_color_0": 21,
        "tile_color_1": 52,
        "tile_color_2": 54,
        "tile_color_3": 83,
        "tile_color_4": 85,
        "tile_color_5": 87,
        "tile_color_6": 98,
        "tile_color_7": 100,
        "tile_color_8": 102,
        "tile_color_9": 104,
        "tile_color_10": 1,
        "tile_color_11": 3,
        "tile_color_12": 5,
        "tile_color_13": 7,
        "tile_color_14": 9,
        "tile_color_15": 32,
        "tile_color_16": 34,
        "tile_color_17": 36,
        "tile_color_18": 38,
        "tile_color_19": 40,
        "tile_color_20": 42,
    },
    riverraid={"player_x": 51, "missile_x": 117, "missile_y": 50, "fuel_meter_high": 55, "fuel_meter_low": 56},
    seaquest={
        "player_x": 70,
        "player_y": 97,
        "player_direction": 86,
        "player_missile_direction": 87,
        "oxygen_meter_value": 102,
        "player_missile_x": 103,
        "num_lives": 59,
        "divers_collected_count": 62,
        "enemy_obstacle_x_0": 30,
        "enemy_obstacle_x_1": 31,
        "enemy_obstacle_x_2": 32,
        "enemy_obstacle_x_3": 33,
        "diver_or_enemy_missile_x_0": 71,
        "diver_or_enemy_missile_x_1": 72,
        "diver_or_enemy_missile_x_2": 73,
        "diver_or_enemy_missile_x_3": 74,
        "score_0": 57,
        "score_1": 58,
    },
    skiing={
        "player_x": 25,
        "clock_m": 104,
        "clock_s": 105,
        "clock_ms": 106,
        "score": 107,
        "object_y_0": 87,
        "object_y_1": 88,
        "object_y_2": 89,
        "object_y_3": 90,
        "object_y_4": 91,
        "object_y_5": 92,
        "object_y_6": 93,
    },
    spaceinvaders={
        "invaders_left_count": 17,
        "player_score": 104,
        "num_lives": 73,
        "player_x": 28,
        "enemies_x": 26,
        "missiles_y": 9,
        "enemies_y": 24,
    },
    tennis={
        "enemy_x": 27,
        "enemy_y": 25,
        "enemy_score": 70,
        "ball_x": 16,
        "ball_y": 17,
        "player_x": 26,
        "player_y": 24,
        "player_score": 69,
    },
    venture={
        "sprite0_y": 20,
        "sprite1_y": 21,
        "sprite2_y": 22,
        "sprite3_y": 23,
        "sprite4_y": 24,
        "sprite5_y": 25,
        "sprite0_x": 79,
        "sprite1_x": 80,
        "sprite2_x": 81,
        "sprite3_x": 82,
        "sprite4_x": 83,
        "sprite5_x": 84,
        "player_x": 85,
        "player_y": 26,
        "current_room": 90,
        "num_lives": 70,
        "score_1_2": 71,
        "score_3_4": 72,
    },
    videopinball={
        "ball_x": 67,
        "ball_y": 68,
        "player_left_paddle_y": 98,
        "player_right_paddle_y": 102,
        "score_1": 48,
        "score_2": 50,
    },
    yarsrevenge={
        "player_x": 32,
        "player_y": 31,
        "player_missile_x": 38,
        "player_missile_y": 37,
        "enemy_x": 43,
        "enemy_y": 42,
        "enemy_missile_x": 47,
        "enemy_missile_y": 46,
    },
)


class AtariWrapper(gym.Wrapper):
    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        ram = self.ale.getRAM()
        game = self.spec._env_name.lower()
        p = ATARI_DICT[game]
        extra_info = {key: ram[p[key]] for key in p}
        info = {**info, **extra_info}
        return obs, reward, done, info


if __name__ == "__main__":
    env = gym.make("ALE/MontezumaRevenge-v5")
    env = AtariWrapper(env)
    env.reset()
    for t in range(30000):
        obs, reward, done, info = env.step(0)
        if t % 10 == 0:
            print(info)
        env.render()
